### ISSUE TITLE
Replace the satellite map tiles with something functional

### ISSUE THREAD

**Issue by DavidEBest** [codefordayton/MCLotLinker#3]
To see the problem:

* Navigate to [GoGetProperties](http://gogetproperties.com/)
* Click on the layers button in the upper right corner of the map.
* Select 'Satellite'
* At this point, the the tiles will be replaced with a MapQuest message saying that the service has been discontinued.

The site references the MapQuest tiles [here](https://github.com/codefordayton/daytonreap/blob/master/static/js/main.js#L170). The tiles should be replaced by another free-to-use (with attribution) tile set, like the [ESRI World Imagery set](https://leaflet-extras.github.io/leaflet-providers/preview/#filter=Esri.WorldImagery).

**Comment by DavidEBest** [comment]
See how it can be done here: https://github.com/codefordayton/daytonreap/pull/81

**Comment by LukeKuenneke** [comment]
On it.

**Comment by DavidEBest** [comment]
Closed by #5. Thanks, @LukeKuenneke !
