### ISSUE TITLE
Improve search performance to match LotLinker

### ISSUE THREAD

**Issue by DavidEBest** [codefordayton/MCLotLinker#4]
There was some work done on this here: https://github.com/codefordayton/daytonreap/issues/67. Want to migrate those changes here?

**Comment by LukeKuenneke** [comment]
I take it I should coordinate with @itopaloglu83 on this.

**Comment by DavidEBest** [comment]
Yeah, generally speaking, the changes here should be good: https://github.com/codefordayton/daytonreap/pull/78

**Comment by DavidEBest** [comment]
Closed by #6. Thanks, @gtempus !
